= GameSquirrel System Internals
Jeff Lassahn
0.1.0, February 23,2025
:copyright: 2025 Jeff Lassahn
:doctype: book
:toc: left
:toc-title: Table of Contents
:title-page:

[preface]
== Preface

TODO This is a book describing the details of the GameSquirrel system software.

== Introduction

The GameSquirrel is awesome.  Here's how it works.

=== References

Other documents useful for reference:

For the Arm Cortex M33 CPU,
	Arm Cortex-M33 Devices Generic User Guide (from Arm)
	Arm Cortex-M33 Processor Technical Reference Manual (from Arm)
	Reference Manual for STM32H523/33xx (ST RM0481)

For the display
	Sitronix ST7789V Datasheet

For the serial RAM...

SD card spec?
USB spec?
FAT filesystem spec?


== Memory Organization

The GameSquirrel has three kinds of system memory:

* 272KBytes of fast SRAM.
* 512KBytes of Flash ROM 
* 4MBytes of slow RAM.

=== Slow RAM

The main memory of the GameSquirrel is a serial RAM chip which provides 4
Megabytes of space.  The game's code and general data are loaded here by
the system software.

The maximum speed of the main memory is about 50 Megabytes per second, which
is much slower than the 250MHz main processor.

The processor has an instruction cache and data cache to make access to the
slow RAM more efficient.  To allow both caches to access the same memory, the
same slow ram memory is mapped to two different address ranges.  If the
memory is accessed through addresses 0x9000000 ... 0x903FFFFF it will be
treated as data memory and accessed through the data cache.  If the memory
is accessed through addresses 0x04000000 ... 0x043FFFFF it will be treated
as executable read-only memory and accessed through the instruction cache.

The two views of memory are aliases of the same RAM, but the two caches
are not kept consistent with each other.  In general, you should only access
read/write data in slow memory through the data cache address range and only
access read-only data or executable code through the instruction cache address
range.  If you attempt to access the same data through both memory ranges,
you must explicitly flush or invalidate the caches to avoid seeing stale
data.

=== Fast RAM

The processor has 272KBytes of SRAM that run at the full CPU speed.  Most
of this memory is available for use by the application, although the top
4KBytes is reserved for use by the system.

The stack is located at the bottom of fast RAM.  Normally 12KBytes are reserved
for the stack, but this can be adjusted in the program configuration file if
one is provided.

The remaining memory can be allocated for application use using
FIXME what system calls?

=== Flash ROM

The processor has 512KBytes of internal flash memory which contains the
system software and related data.  The only two memory addresses in Flash
which are guaranteed to be consistent across versions of the system software
are

* The interrupt vector table, which is at address 0x08000000.
* The system library table, which is at address 0x08000400.

=== Memory map

[cols=".^1,.^1,.^2"]
|===
| Memory |Address | Purpose

.8+| DCACHE RAM
| 0x903F_FFFF
.2+| System Data

| 0x903F_C000

| 0x903F_BFFF
.2+| Application Heap

| ...

| ...
.2+| Application Data

| ...

| ...
.2+| ALIAS (Application Code)

| 0x9000_0000

.6+| SRAM
| 0x2004_3FFF
.2+| System Data

| 0x2004_3000

| 0x2004_2FFF
.2+| Application Heap

| 0x2000_3000

| 0x2000_2FFF
.2+| Stack

| 0x2000_0000

.6+| Flash ROM
| 0x0807_FFFF
.2+| System Code

| ...

| ...
.2+| System Library Table

| 0x0800_0400

| ...
.2+| System Interrupt Table

| 0x0800_0000

.8+| ICACHE RAM
| 0x043F_FFFF
.2+| ALIAS (System Data)

| 0x043F_C000

| 0x043F_BFFF
.2+| ALIAS (Application Heap)

| ...

| ...
.2+| ALIAS (Application Data)

| ...

| ...
.2+| Application Code

| 0x0400_0000
|===

== Interfaces to Peripherals

=== Display

Uses ST7789V controller
On SPI2


=== Slow Memory

On OCTOSPI in Quad mode.

=== SD Cards

On SPI1

=== Audio

On DAC1 Channel 1 and 2, 48KHz
Use DMA to send blocks, witn interrupt.

=== Joystick
On ADC1 Input 0 and 1

=== Buttons

=== Indicator LEDs

=== USB

=== Battery Voltage

== Configuration of the Microcontroller

=== Clocks

LSE is 32768Hz crystal for realtime clock on OSC32

HSE is 16MHz oscillator
HSE drives PLLs
	PLL1/VCO 500MHz
	PLL1/P   CPU 250MHz
	PLL1/Q   SPI2 62.5MHz
	PLL1/R

	PLL2/VCO 200MHz
	PLL2/P   SPI1 25MHz
	PLL2/Q
	PLL2/R   OCTOSPI 100MHz

	PLL3/VCO 192MHz
	PLL3/P
	PLL3/Q   USB 48MHz
	PLL3/R   DAC timer LPTIM2 48MHz

FIXME HSI48 can be used for USB, probably use PLL instead


=== Interrupts

=== Memory

=== DMA

GPDMA1 Channel 5 -- DMA channel for Audio (large FIFO, no 2D addressing)
GPDMA1 Channel 6 -- DMA channel for video buffer copies (large FIFO 2d address)

=== Timers

Audio timing uses LPTIM2 timer clocked from PLL3/R at 192MHz
TIM2 is used as a 32 bit free-running 1MHz clock.
TIM1_CH2 and TIM1_CH3 control Indicator LEDs.
LPTIM1 can be used to measure PLL2/P or PLL3/R


=== Analog Inputs

ADC1
	input 0, Joystick X
	input 1, Joystick Y
	input 14, Unused pin PA2
	input 15, Unused pin PA3
	input 17, Vrefint  1.216v
ADC2
	input 0, Joystick X
	input 1, Joystick Y
	input 14, Unused pin PA2
	input 15, Unused pin PA3
	input 16, Vbat

== The Game Program and Filesystem

=== The program configuration file

=== The main executable

